name: Docker build & push Docker Hub

on:
  push:
    branches: [master]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: myreadme

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DOCKER LOGIN
        run: docker login -u ${{ env.DOCKER_USER }} -p ${{ env.DOCKER_PASSWORD }}

      - name: BUILDING FOR PRODUCTION
        run: npm i && npm run build

      - name: BUILD IMAGE WITH COMMIT SHA
        run: docker build . -t ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: RETAG IMAGE LATEST WITH DIGEST FROM PREVIOUS IMAGE
        run: |
          IMAGE_ID=$(docker images | grep $DOCKER_REGISTRY\/${{ env.DOCKER_IMAGE_NAME }} | head -n1 | awk '{print $3}')
          docker tag $IMAGE_ID ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: PUSH IMAGE LATEST AND COMMIT SHA
        run: |
          docker push ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
